# Example Site settings

#google_analytics: UA-NNNNNNNN-N

header_pages:
   - index.md
   - sknux.md
   - H4izenb3rg.md
   - SrtLillithh3x.md
   - attej.md
   - tobe.md
   - cfsantos.md
   - confs.md

footer: 'read phrack magazine <a href="http://phrack.org">phrack.org</a>'

style: hacker # dark (default) or light
# listen_for_clients_preferred_style: true # true or false (default)

plugins:
  - jekyll-seo-tag
